site_url : https://asalvadorc.github.io/BBDD_Tema3
site_name: BD - Bases de Dades
theme: 
  name: readthedocs
  logo: assets/logocaminas.png

extra_css:
  - css/extra.css  
nav:
  - Tema 3 Model Relacional:
    - Objectius i coneixements previs: BD-T03_Model_Relacional/objectius_i_coneixements_previs.md
    - 1. Introducció: BD-T03_Model_Relacional/1_introducci.md
    - 2. Estructura del Model Relacional: BD-T03_Model_Relacional/2_estructura_del_model_relacional.md
    - 3. Restriccions: BD-T03_Model_Relacional/3_restriccions.md
    - 4. Tranformació del M. E/R al M. Relacional: BD-T03_Model_Relacional/4_tranformaci_del_m_er_al_m_relacional.md
    - 5. Llenguatges relacionals: BD-T03_Model_Relacional/5_llenguatges_relacionals.md
    - 6. Exercicis: BD-T03_Model_Relacional/6_exercicis.md
    
